export const templates = [
  {
    id: "ai-studio",
    title: "AI Studio — Cinematic Capsule Suite",
    desc: "A premium creative agency landing page blueprint featuring interactive Three.js liquid canvas, dark obsidian aesthetic, and fluid motion.",
    img: "/cyber_dashboard.jpg",
    prompt: "A cinematic creative agency landing page named 'AI Studio', dark mode obsidian background #060507, 3D interactive WebGL liquid metal sphere, glassmorphic floating panels, sleek typography, Framer motion smooth transitions, responsive breakpoints, high contrast cyan and purple ambient glow --ar 16:9 --v 6.1",
    isPro: true,
    tags: ["Landing Page", "Three.js", "Next.js", "WebGL", "Agency"],
    category: "landing-pages",
    category_id: "cat-1",
    tool: "Midjourney v6.1 & Claude 3.7",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-1",
    title: "Cinematic Cyber Android Portrait",
    desc: "A highly detailed, neon-lit cyberpunk portrait of a cybernetic android with volumetric atmospheric rim lighting.",
    img: "/cyber_portrait.jpg",
    prompt: "A cinematic portrait of a female android in a cyberpunk city, rainy neon streets, sharp focus, 85mm lens, f/1.8, unreal engine 5 render, volumetric lighting, photorealistic --ar 16:9 --v 6.1 --style raw",
    isPro: true,
    tags: ["Character", "Sci-Fi", "Cinematic", "Portrait"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-2",
    title: "Dark Cyber Dashboard UI",
    desc: "Dark mode web dashboard, glassmorphism, glowing neon telemetry accents, perfect for cybernetic tools and consoles.",
    img: "/cyber_dashboard.jpg",
    prompt: "UI/UX design of a modern dark mode web dashboard, glassmorphism, cyberpunk theme, glowing neon accents, intricate data visualizations, high resolution, dark obsidian background --ar 16:9 --v 6.1",
    isPro: false,
    tags: ["UI/UX", "Web Design", "Cyberpunk", "Dark Mode"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "v0 by Vercel & Midjourney v6.1",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-3",
    title: "Holographic Liquid 3D Showcase",
    desc: "Mesmerizing 3D liquid metal simulations with holographic cyan and magenta geometry for luxury product backdrops.",
    img: "/holographic_3d.jpg",
    prompt: "3D render of abstract liquid metal and holographic geometry, iridescent magenta and cyan colors, smooth flowing waves, macro photography, octane render, highly detailed, 8k --ar 16:9 --s 750",
    isPro: true,
    tags: ["3D", "Abstract", "Holographic", "Render"],
    category: "ecommerce",
    category_id: "cat-3",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-4",
    title: "Retro 80s Synthwave Poster",
    desc: "Outrun-style digital sun setting over a neon grid with palm silhouettes. The quintessential retro aesthetic.",
    img: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=800&auto=format&fit=crop",
    prompt: "Retro 80s synthwave landscape, glowing neon grid, digital sunset, outrun aesthetic, purple and pink color palette, palm trees silhouette, vintage sci-fi poster art --ar 16:9 --style raw",
    isPro: false,
    tags: ["Retro", "Poster", "Neon", "Landscape"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "FLUX.1 Schnell",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-5",
    title: "Epic Fantasy Highlands Landscape",
    desc: "A sweeping fantasy vista with dramatic god rays and cinematic golden hour composition.",
    img: "https://images.unsplash.com/photo-1501854140801-50d01698950b?q=80&w=800&auto=format&fit=crop",
    prompt: "Epic fantasy landscape, dramatic mountains, golden hour lighting, lush forests, distant castle, god rays, cinematic composition, highly detailed, fantasy illustration style, 8k resolution --ar 16:9",
    isPro: true,
    tags: ["Fantasy", "Landscape", "Cinematic", "Environment"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-6",
    title: "Luxury Timepiece Product Showcase",
    desc: "A sleek, dramatic lighting prompt for premium product reveals, watches, and luxury goods.",
    img: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?q=80&w=800&auto=format&fit=crop",
    prompt: "Cinematic product reveal video, luxury watch floating in dark void, soft specular highlights, 4K slow motion, macro lens, smooth camera orbit, professional studio lighting, dramatic shadows --ar 16:9",
    isPro: true,
    tags: ["Ecommerce", "Product", "Cinematic", "Brand"],
    category: "ecommerce",
    category_id: "cat-3",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-7",
    title: "Watercolour Botanical Print",
    desc: "Delicate botanical illustration in classic watercolour style. Great for art prints and packaging.",
    img: "https://images.unsplash.com/photo-1490750967868-88df5691cc1a?q=80&w=800&auto=format&fit=crop",
    prompt: "Watercolour botanical illustration, wildflowers and leaves, soft pastel palette, loose brushwork, white paper background, art print quality, professional illustration --ar 16:9",
    isPro: false,
    tags: ["Watercolour", "Nature", "Print", "Botanical"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "FLUX.1 Pro",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-8",
    title: "Conversion SaaS Hero Landing Page",
    desc: "A high-converting SaaS landing page with dark obsidian background, glassmorphic cards, and crisp metrics.",
    img: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?q=80&w=800&auto=format&fit=crop",
    prompt: "Modern SaaS website landing page, dark mode, glassmorphism hero section, gradient accents in purple and blue, bold typography, floating UI mockups, CTA buttons, clean grid layout --ar 16:9 --v 6.1",
    isPro: true,
    tags: ["SaaS", "Landing Page", "Dark Mode", "Web"],
    category: "landing-pages",
    category_id: "cat-1",
    tool: "Claude 3.7 Sonnet & v0",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-9",
    title: "Neo-Tokyo Cyberpunk Alleyway",
    desc: "Gritty neon-lit street scene with high definition reflections, steam vents, and rain-slicked asphalt.",
    img: "https://images.unsplash.com/photo-1542382156909-92f758782a20?q=80&w=800&auto=format&fit=crop",
    prompt: "Cyberpunk alleyway, neon signs in kanji, rainy night, reflections on wet pavement, volumetric fog, cinematic lighting, 8k resolution, octane render --ar 16:9",
    isPro: true,
    tags: ["Cyberpunk", "City", "Neon", "Cinematic"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-10",
    title: "Minimal Geometric Tech Monogram",
    desc: "Clean geometric logo concept for tech startups. Scalable vector aesthetic with negative space interplay.",
    img: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=800&auto=format&fit=crop",
    prompt: "Minimalist logo design, geometric shapes, tech startup, flat vector style, negative space, modern typography, white background --style raw",
    isPro: false,
    tags: ["Logo", "Design", "Minimal", "Tech"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "FLUX.1 Schnell",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-11",
    title: "Sci-Fi Plasma Rifle Blueprint",
    desc: "Detailed technical schematic concept art of a futuristic plasma weapon with blueprint annotations.",
    img: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?q=80&w=800&auto=format&fit=crop",
    prompt: "Sci-fi weapon concept art, plasma rifle, futuristic design, technical blueprint styling, side view, detailed mechanical parts, metallic finish --ar 16:9",
    isPro: true,
    tags: ["Sci-Fi", "Concept Art", "Weapon", "Design"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-12",
    title: "Luxury Apparel Mobile Storefront",
    desc: "Modern fashion e-commerce mobile application interface with editorial typography and high-end cards.",
    img: "https://images.unsplash.com/photo-1555529902-5261145633bf?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, mobile app interface, fashion e-commerce, modern, elegant, clean typography, large product images, beige and white color scheme --ar 9:16",
    isPro: true,
    tags: ["UI/UX", "Mobile", "App", "Fashion"],
    category: "mobile-apps",
    category_id: "cat-5",
    tool: "Claude 3.7 & v0",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-13",
    title: "Cosmic Nebula Deep Space Monitor",
    desc: "Astronomical telemetry visualization of deep space nebula with vibrant cosmic dust and infrared spectral hues.",
    img: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=800&auto=format&fit=crop",
    prompt: "Deep space nebula, vibrant cosmic gas clouds, millions of stars, astronomical visualization, James Webb telescope style, highly detailed, 8k --ar 16:9",
    isPro: false,
    tags: ["Space", "Cosmic", "Astronomy", "Background"],
    category: "saas-dashboards",
    category_id: "cat-6",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-14",
    title: "Swiss Typographic Festival Poster",
    desc: "Bold international typographic style poster with stark asymmetric layout and high contrast grid.",
    img: "https://images.unsplash.com/photo-1563298723-dcfebaa392e3?q=80&w=800&auto=format&fit=crop",
    prompt: "Swiss design poster, bold typography, music festival event, high contrast, red and black color scheme, minimalist layout, grid system --ar 2:3",
    isPro: false,
    tags: ["Typography", "Poster", "Design", "Event"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "FLUX.1 Pro",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-15",
    title: "Metropolitan Traffic Hyper-lapse Stream",
    desc: "Long exposure telemetry visual with light trails, neon city highway intersections, and fast motion aesthetics.",
    img: "https://images.unsplash.com/photo-1494522855154-9297ac14b55f?q=80&w=800&auto=format&fit=crop",
    prompt: "Hyper-lapse video sequence, city traffic at night, long exposure light trails, drone perspective, fast motion, neon city lights --ar 16:9",
    isPro: true,
    tags: ["Video", "City", "Hyper-lapse", "Night"],
    category: "saas-dashboards",
    category_id: "cat-6",
    tool: "Runway Gen-3 Alpha",
    toolUrl: "https://runwayml.com"
  },
  {
    id: "tpl-16",
    title: "Isometric 3D Tech Icon Ecosystem",
    desc: "Glossy plastic isometric 3D icons for developer tools, databases, cloud clusters, and microservices.",
    img: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?q=80&w=800&auto=format&fit=crop",
    prompt: "3D icon set, technology theme, isometric perspective, glossy plastic materials, soft studio lighting, pastel background, cute aesthetic --ar 16:9",
    isPro: true,
    tags: ["3D", "Icons", "Tech", "UI"],
    category: "saas-dashboards",
    category_id: "cat-6",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-17",
    title: "Minimalist Architectural Cantilever Villa",
    desc: "Modern luxury villa exterior at sunset with floor-to-ceiling glass and geometric cantilever overhangs.",
    img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
    prompt: "Architectural visualization, modern luxury villa, glass walls, infinity pool, sunset lighting, photorealistic, V-ray render, 8k --ar 16:9",
    isPro: false,
    tags: ["Architecture", "3D", "Render", "Exterior"],
    category: "ecommerce",
    category_id: "cat-3",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-18",
    title: "Cryptocurrency Terminal & Liquidity HUD",
    desc: "Advanced trading dashboard interface with orderbook depth charts, real-time candles, and dark mode telemetry.",
    img: "https://images.unsplash.com/photo-1621504450181-5d156f8946db?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, cryptocurrency trading dashboard, dark mode, glowing neon charts, complex data visualization, futuristic interface --ar 16:9",
    isPro: true,
    tags: ["UI/UX", "Crypto", "Dashboard", "Dark Mode"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "Claude 3.7 Sonnet & v0",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-19",
    title: "Web3 Non-Custodial Mobile Wallet UI",
    desc: "Glassmorphic mobile interface for crypto asset tracking, biometric send transactions, and staking rewards.",
    img: "https://images.unsplash.com/photo-1518066000714-58c45f1a2c0a?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, modern mobile crypto wallet app, dark obsidian UI, frosted glass cards, glowing balance chart, clean bottom nav, iOS typography --ar 9:16",
    isPro: false,
    tags: ["Mobile", "Crypto", "Web3", "UI/UX"],
    category: "mobile-apps",
    category_id: "cat-5",
    tool: "v0 by Vercel",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-20",
    title: "Mindfulness & Sleep Meditation App",
    desc: "Serene mobile interface with ambient sound generators, circular breath timers, and soothing pastel gradients.",
    img: "https://images.unsplash.com/photo-1589903308904-1010c2294adc?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, mindfulness and sleep meditation mobile app, soothing deep indigo background, glowing breath ring, minimalist icons, serene aesthetic --ar 9:16",
    isPro: true,
    tags: ["Mobile", "Meditation", "Wellness", "UI/UX"],
    category: "mobile-apps",
    category_id: "cat-5",
    tool: "Claude 3.7 Sonnet",
    toolUrl: "https://anthropic.com"
  },
  {
    id: "tpl-21",
    title: "Creative Agency Panoramic Studio Site",
    desc: "Editorial agency landing page with full-bleed video backgrounds, large scale sans-serif type, and interactive project cards.",
    img: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    prompt: "Creative design studio website, editorial typography, dark slate background, interactive project showcase, smooth scrolling layout, award winning UI --ar 16:9 --v 6.1",
    isPro: true,
    tags: ["Agency", "Portfolio", "Landing Page", "Editorial"],
    category: "landing-pages",
    category_id: "cat-1",
    tool: "Midjourney v6.1 & Claude 3.7",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-22",
    title: "Abstract Liquid Chrome 3D Waves",
    desc: "Iridescent molten metal ripples with studio reflections. Ideal for luxury brand backgrounds and Hero section textures.",
    img: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=800&auto=format&fit=crop",
    prompt: "3D render of liquid chrome waves, abstract fluid dynamics, studio lighting reflections, hyper-detailed surface tension, monochromatic with violet tint --ar 16:9",
    isPro: false,
    tags: ["3D", "Chrome", "Liquid", "Abstract"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-23",
    title: "Brutalist Architecture Exhibition Site",
    desc: "Monochrome brutalist landing page with raw concrete imagery, bold structural grids, and architectural blueprints.",
    img: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=800&auto=format&fit=crop",
    prompt: "Brutalist architectural exhibition website, raw concrete aesthetics, high contrast monochrome typography, minimalist navigation, structured grid --ar 16:9",
    isPro: true,
    tags: ["Brutalist", "Architecture", "Landing Page", "Monochrome"],
    category: "landing-pages",
    category_id: "cat-1",
    tool: "Claude 3.7 Sonnet & v0",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-24",
    title: "Ceramic Artisan E-Commerce Capsule",
    desc: "E-Commerce lookbook page with warm terracotta and travertine textures, ceramic product closeups, and organic layout.",
    img: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=800&auto=format&fit=crop",
    prompt: "Luxury ceramic artisan ecommerce shop, warm sandstone and travertine background, studio product photography, clean purchase modal, minimalist aesthetic --ar 16:9",
    isPro: false,
    tags: ["Ecommerce", "Ceramic", "Minimalist", "Shop"],
    category: "ecommerce",
    category_id: "cat-3",
    tool: "FLUX.1 Pro",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-25",
    title: "Fine Dining Restaurant Ordering App",
    desc: "Appetizing dark mode mobile food ordering interface with rich culinary imagery, sommelier notes, and chef specials.",
    img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, fine dining mobile app, restaurant tasting menu, appetizing culinary photography, dark bronze and charcoal colors, elegant serif typography --ar 9:16",
    isPro: true,
    tags: ["UI/UX", "Mobile", "App", "Food"],
    category: "mobile-apps",
    category_id: "cat-5",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-26",
    title: "Enterprise Multi-Cloud Infrastructure Telemetry",
    desc: "Kubernetes cluster management console with node health gauges, latency heatmaps, and zero-trust security feeds.",
    img: "https://images.unsplash.com/photo-1498084393753-b411b2d26b34?q=80&w=800&auto=format&fit=crop",
    prompt: "Enterprise SaaS monitoring interface, Kubernetes cluster telemetry, dark carbon background, emerald latency indicators, real-time node map --ar 16:9",
    isPro: true,
    tags: ["SaaS", "DevOps", "Telemetry", "Infrastructure"],
    category: "saas-dashboards",
    category_id: "cat-6",
    tool: "Claude 3.7 Sonnet & v0",
    toolUrl: "https://v0.dev"
  },
  {
    id: "tpl-27",
    title: "Coastal Archipelago Aerial Flyover",
    desc: "Cinematic drone establishing sequence over turquoise reef shallows and granite coastlines for video backgrounds.",
    img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop",
    prompt: "Cinematic drone video, aerial flyover, tropical archipelago, turquoise ocean, white sand beach, golden hour lighting, smooth cinematic motion --ar 16:9",
    isPro: false,
    tags: ["Video", "Drone", "Landscape", "Cinematic"],
    category: "saas-dashboards",
    category_id: "cat-6",
    tool: "Runway Gen-3 Alpha",
    toolUrl: "https://runwayml.com"
  },
  {
    id: "tpl-28",
    title: "Cinema Noir Film Noir Poster",
    desc: "High-contrast silhouette movie poster with Venetian blind light casting and dramatic serif typography.",
    img: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?q=80&w=800&auto=format&fit=crop",
    prompt: "Minimalist movie poster, neo-noir thriller, silhouette through Venetian blinds, dramatic shadows, crimson title typography, negative space --ar 2:3",
    isPro: true,
    tags: ["Poster", "Minimalist", "Design", "Movie"],
    category: "portfolios",
    category_id: "cat-4",
    tool: "FLUX.1 Pro",
    toolUrl: "https://blackforestlabs.ai"
  },
  {
    id: "tpl-29",
    title: "Neon Wireframe Digital Elevation Mesh",
    desc: "Glowing vector topographical landscape with isometric contour lines and cybernetic neon teal elevation grades.",
    img: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop",
    prompt: "Abstract technology background, glowing neon wireframe topology, 3d grid terrain, digital landscape, cyan and purple colors --ar 16:9",
    isPro: true,
    tags: ["Background", "Tech", "3D", "Wireframe"],
    category: "cyber-tech",
    category_id: "cat-2",
    tool: "Midjourney v6.1",
    toolUrl: "https://midjourney.com"
  },
  {
    id: "tpl-30",
    title: "Bento Box Creative Director Portfolio",
    desc: "Modular bento box portfolio website layout featuring live case study tiles, glowing stats, and dark obsidian aesthetic.",
    img: "https://images.unsplash.com/photo-1517292987719-0369a794ec0f?q=80&w=800&auto=format&fit=crop",
    prompt: "UI/UX design, personal portfolio website, bento box grid layout, modern aesthetic, dark mode, vibrant accent colors, rounded cards --ar 16:9",
    isPro: true,
    tags: ["UI/UX", "Web Design", "Portfolio", "Bento"],
    category: "landing-pages",
    category_id: "cat-1",
    tool: "v0 by Vercel & Claude 3.7",
    toolUrl: "https://v0.dev"
  }
];
